---
-
  hosts: windows
  vars:
    jobname:
     - "NOVO_INDEX_DEFRAG"
     - "NOVOHISTORY_DIFF"
     - "NOVOHISTORY_LOG"
     - "NOVOHISTORY_MAINT"
     - "NOVOJACKPOT_DIFF"
     - "NOVOJACKPOT_LOG"
     - "NOVOJACKPOT_MAINT"
     - "NOVOJACKPOT_MONITOR_CLEANER"
     - "NOVOJACKPOT_MONITOR_TOOL"
     - "NOVOSTAT_DIFF"
     - "NOVOSTAT_LOG"
     - "NOVOSTAT_MAINT"
     - "NOVOTITO_DIFF"
     - "NOVOTITO_LOG"
     - "NOVOTITO_MAINT"
     - "NOVOWARE_DIFF"
     - "NOVOWARE_LOG"
     - "NOVOWARE_MAINT"
    databasename:
     - "NovoJackpot"
     - "NovoHistory"
     - "NovoStat"
     - "NovoWare"
  tasks:
    - name: Disable jobs
      register: result
      win_mssql_db_job:
       jobname: "{{ item }}"
       enable: 0
       failed_when: result.output != True
      with_items:
        "{{ jobname }}"
       
    - name: Backup database
      register: result
      win_mssql_db_backup:
       database: "{{ item }}"
       directory: "C:\\"
       failed_when: result.output != True
      with_items:
        "{{ databasename }}"

    - name: Enable jobs
      register: result
      win_mssql_db_job:
       jobname: "{{ item }}"
       enable: 1
       failed_when: result.output != True
      with_items:
        "{{ jobname }}"

