---
-
  hosts: windows
  vars:
    databasename:
     - "NovoWare"
  tasks:       
    - name: Backup database
      register: result
      win_mssql_db_backup:
       database: "{{ item }}"
       directory: "C:\\"
       failed_when: result.output != True
      with_items:
        "{{ databasename }}"
    

