---
-
  hosts: windows
  vars:
    uri_start: "http://localhost:14500/IMdiLoaderService/Start"
    uri_stop: "http://localhost:14500/IMdiLoaderService/Stop"
    uri_remove_drvier: "http://localhost:14500/IMdiLoaderService/RemoveDriver"
    uri_get_mdis: "http://localhost:14500/IMdiLoaderService/GetMdis"
    uri_start_load_driver: "http://localhost:14500/IMdiLoaderService/StartLoadDriver"
    HWA: "00409D70C330"
    driver: "IGT"
  tasks:
    - name: Start load driver
      win_uri:
       url: "{{uri_start_load_driver}}"
       method: "POST"
       body: "{ 'Driver' : 'MDI3_IGT' , 'Hwa' : '{{HWA}}' }"



